### ISSUE TITLE
The error message pops up "read only property 'asyncIterator'"

### ISSUE THREAD

**Issue by Polinden** [mvoidex/atom-haskell-hsdev#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-haskell-hsdev](https://github.com/mvoidex/atom-haskell-hsdev) package 0.0.1

### Stack Trace

Failed to activate the atom-haskell-hsdev package

```
At Cannot assign to read only property 'asyncIterator' of function 'function Symbol() { [native code] }'

TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Symbol() { [native code] }'
    at /packages/atom-haskell-hsdev/lib/hsdev/interactive-process.js:10:22)
    at /packages/atom-haskell-hsdev/lib/hsdev/interactive-process.js:218:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-haskell-hsdev/lib/hsdev/hsdev-process-real.js:4:31)
    at /packages/atom-haskell-hsdev/lib/hsdev/hsdev-process-real.js:328:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-haskell-hsdev/lib/hsdev/index.js:5:30)
    at /packages/atom-haskell-hsdev/lib/hsdev/index.js:185:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/atom-haskell-hsdev/lib/atom-haskell-hsdev.js:3:17)
    at /packages/atom-haskell-hsdev/lib/atom-haskell-hsdev.js:62:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
```

### Commands

```
     -1:41.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-haskell-hsdev 0.0.1 
ide-haskell 2.4.1 
ide-haskell-cabal 2.3.0 
ide-haskell-repl 0.9.0 
language-haskell 1.19.1 
```

**Comment by mvoidex** [comment]
Sorry for long delay. Atom plugin wasn't fully implemented and now freezed as long as I have no time for it.
